using IBKRProvider.Models;

namespace IBKRProvider.Utilities
{
    public static class IBKRProviderErrorCodes
    {
        public static List<ProviderErrorDef> ErrorDef = new List<ProviderErrorDef>()
        {
            new ProviderErrorDef() { ErrCode= 100, RootsErr= 140, Desc= "Max rate of messages per second has been exceeded."},
            new ProviderErrorDef() { ErrCode= 101, RootsErr= 140, Desc= "Max number of tickers has been reached."},
            new ProviderErrorDef() { ErrCode= 102, RootsErr= 120, Desc= "Duplicate ticker ID."},
            new ProviderErrorDef() { ErrCode= 103, RootsErr= 130, Desc= "Duplicate order ID."},
            new ProviderErrorDef() { ErrCode= 104, RootsErr= 131, Desc= "Can’t modify a filled order."},
            new ProviderErrorDef() { ErrCode= 105, RootsErr= 132, Desc= "Order being modified does not match original order."},
            new ProviderErrorDef() { ErrCode= 106, RootsErr= 107, Desc= "Can’t transmit order ID="},
            new ProviderErrorDef() { ErrCode= 107, RootsErr= 108, Desc= "Cannot transmit incomplete order."},
            new ProviderErrorDef() { ErrCode= 109, RootsErr= 106, Desc= "Price is out of the range defined by the Percentage setting at order defaults frame. The order will not be transmitted."},
            new ProviderErrorDef() { ErrCode= 110, RootsErr= 106, Desc= "The price does not conform to the minimum price variation for this contract."},
            new ProviderErrorDef() { ErrCode= 111, RootsErr= 106, Desc= "The TIF (Tif type) and the order type are incompatible."},
            new ProviderErrorDef() { ErrCode= 113, RootsErr= 106, Desc= "The Tif option should be set to DAY for MOC and LOC orders."},
            new ProviderErrorDef() { ErrCode= 114, RootsErr= 107, Desc= "Relative orders are valid for stocks only."},
            new ProviderErrorDef() { ErrCode= 115, RootsErr= 107, Desc= "“Relative orders for US stocks can only be submitted to SMART, SMART_ECN, INSTINET, or PRIMEX.”"},
            new ProviderErrorDef() { ErrCode= 116, RootsErr= 107, Desc= "The order cannot be transmitted to a dead exchange."},
            new ProviderErrorDef() { ErrCode= 117, RootsErr= 133, Desc= "The block order size must be at least 50."},
            new ProviderErrorDef() { ErrCode= 118, RootsErr= 107, Desc= "VWAP orders must be routed through the VWAP exchange."},
            new ProviderErrorDef() { ErrCode= 119, RootsErr= 107, Desc= "Only VWAP orders may be placed on the VWAP exchange."},
            new ProviderErrorDef() { ErrCode= 120, RootsErr= 107, Desc= "It is too late to place a VWAP order for today."},
            new ProviderErrorDef() { ErrCode= 121, RootsErr= 106, Desc= "“Invalid BD flag for the order. Check “”Destination”” and “”BD”” flag.”"},
            new ProviderErrorDef() { ErrCode= 122, RootsErr= 106, Desc= "No request tag has been found for order="},
            new ProviderErrorDef() { ErrCode= 123, RootsErr= 105, Desc= "No record is available for conid="},
            new ProviderErrorDef() { ErrCode= 124, RootsErr= 107, Desc= "No market rule is available for conid="},
            new ProviderErrorDef() { ErrCode= 125, RootsErr= 106, Desc= "Buy price must be the same as the best asking price."},
            new ProviderErrorDef() { ErrCode= 126, RootsErr= 106, Desc= "Sell price must be the same as the best bidding price."},
            new ProviderErrorDef() { ErrCode= 129, RootsErr= 107, Desc= "VWAP orders must be submitted at least three minutes before the start time."},
            new ProviderErrorDef() { ErrCode= 131, RootsErr= 106, Desc= "“The sweep-to-fill flag and display size are only valid for US stocks routed through SMART, and will be ignored.”"},
            new ProviderErrorDef() { ErrCode= 132, RootsErr= 107, Desc= "This order cannot be transmitted without a clearing account."},
            new ProviderErrorDef() { ErrCode= 133, RootsErr= 100, Desc= "Submit new order failed."},
            new ProviderErrorDef() { ErrCode= 134, RootsErr= 100, Desc= "Modify order failed."},
            new ProviderErrorDef() { ErrCode= 135, RootsErr= 105, Desc= "Can’t find order with ID ="},
            new ProviderErrorDef() { ErrCode= 136, RootsErr= 100, Desc= "This order cannot be cancelled."},
            new ProviderErrorDef() { ErrCode= 137, RootsErr= 100, Desc= "VWAP orders can only be cancelled up to three minutes before the start time."},
            new ProviderErrorDef() { ErrCode= 138, RootsErr= 104, Desc= "Could not parse ticker request="},
            new ProviderErrorDef() { ErrCode= 139, RootsErr= 104, Desc= "Parsing error="},
            new ProviderErrorDef() { ErrCode= 140, RootsErr= 106, Desc= "The size value should be an integer="},
            new ProviderErrorDef() { ErrCode= 141, RootsErr= 106, Desc= "The price value should be a double="},
            new ProviderErrorDef() { ErrCode= 142, RootsErr= 101, Desc= "Institutional customer account does not have account info"},
            new ProviderErrorDef() { ErrCode= 143, RootsErr= 106, Desc= "Requested ID is not an integer number."},
            new ProviderErrorDef() { ErrCode= 144, RootsErr= 106, Desc= "“Order size does not match total share allocation. To adjust the share allocation, right-click on the order and select â€œModify > Share Allocation.â€?”"},
            new ProviderErrorDef() { ErrCode= 145, RootsErr= 103, Desc= "Error in validating entry fields –"},
            new ProviderErrorDef() { ErrCode= 146, RootsErr= 100, Desc= "Invalid trigger method."},
            new ProviderErrorDef() { ErrCode= 147, RootsErr= 108, Desc= "The conditional contract info is incomplete."},
            new ProviderErrorDef() { ErrCode= 148, RootsErr= 100, Desc= "Conditional submission of orders is supported for Limit, Market, MidPrice, Relative and Snap order types only. Conditional cancelation of orders is supported for Limit and MidPrice order types only."},
            new ProviderErrorDef() { ErrCode= 151, RootsErr= 101, Desc= "This order cannot be transmitted without a user name."},
            new ProviderErrorDef() { ErrCode= 152, RootsErr= 106, Desc= "“The “”hidden”” order attribute may not be specified for this order.”"},
            new ProviderErrorDef() { ErrCode= 153, RootsErr= 106, Desc= "EFPs can only be limit orders."},
            new ProviderErrorDef() { ErrCode= 154, RootsErr= 106, Desc= "Orders cannot be transmitted for a halted security."},
            new ProviderErrorDef() { ErrCode= 155, RootsErr= 101, Desc= "A sizeOp order must have a user name and account."},
            new ProviderErrorDef() { ErrCode= 156, RootsErr= 106, Desc= "A SizeOp order must go to IBSX"},
            new ProviderErrorDef() { ErrCode= 157, RootsErr= 106, Desc= "An order can be EITHER Iceberg or Discretionary. Please remove either the Discretionary amount or the Display size."},
            new ProviderErrorDef() { ErrCode= 158, RootsErr= 106, Desc= "You must specify an offset amount or a percent offset value."},
            new ProviderErrorDef() { ErrCode= 159, RootsErr= 106, Desc= "The percent offset value must be between 0% and 100%."},
            new ProviderErrorDef() { ErrCode= 160, RootsErr= 106, Desc= "The size value cannot be zero."},
            new ProviderErrorDef() { ErrCode= 161, RootsErr= 100, Desc= "Cancel attempted when order is not in a cancellable state. Order permId ="},
            new ProviderErrorDef() { ErrCode= 162, RootsErr= 118, Desc= "Historical market data Service error message."},
            new ProviderErrorDef() { ErrCode= 163, RootsErr= 106, Desc= "The price specified would violate the percentage constraint specified in the default order settings."},
            new ProviderErrorDef() { ErrCode= 164, RootsErr= 100, Desc= "There is no market data to check price percent violations."},
            new ProviderErrorDef() { ErrCode= 165, RootsErr= 111, Desc= "Historical market Data Service query message."},
            new ProviderErrorDef() { ErrCode= 166, RootsErr= 112, Desc= "HMDS Expired Contract Violation."},
            new ProviderErrorDef() { ErrCode= 167, RootsErr= 106, Desc= "VWAP order time must be in the future."},
            new ProviderErrorDef() { ErrCode= 168, RootsErr= 106, Desc= "Discretionary amount does not conform to the minimum price variation for this contract."},
            new ProviderErrorDef() { ErrCode= 200, RootsErr= 100, Desc= "The contract description specified for is ambiguous"},
            new ProviderErrorDef() { ErrCode= 201, RootsErr= 100, Desc= "Order rejected – Reason="},
            new ProviderErrorDef() { ErrCode= 202, RootsErr= 134, Desc= "Order cancelled – Reason="},
            new ProviderErrorDef() { ErrCode= 203, RootsErr= 107, Desc= "The security is not available or allowed for this account."},
            new ProviderErrorDef() { ErrCode= 300, RootsErr= 105, Desc= "Can’t find EId with ticker Id="},
            new ProviderErrorDef() { ErrCode= 301, RootsErr= 100, Desc= "Invalid ticker action="},
            new ProviderErrorDef() { ErrCode= 302, RootsErr= 104, Desc= "Error parsing stop ticker string="},
            new ProviderErrorDef() { ErrCode= 303, RootsErr= 106, Desc= "Invalid action="},
            new ProviderErrorDef() { ErrCode= 304, RootsErr= 106, Desc= "Invalid account value action="},
            new ProviderErrorDef() { ErrCode= 305, RootsErr= 104, Desc= "“Request parsing error, the request has been ignored.”"},
            new ProviderErrorDef() { ErrCode= 306, RootsErr= 100, Desc= "Error processing DDE request="},
            new ProviderErrorDef() { ErrCode= 307, RootsErr= 106, Desc= "Invalid request topic="},
            new ProviderErrorDef() { ErrCode= 308, RootsErr= 100, Desc= "Unable to create the ‘API’ page in TWS as the maximum number of pages already exists."},
            new ProviderErrorDef() { ErrCode= 309, RootsErr= 100, Desc= "“Max number (3) of market depth requests has been reached. Note= TWS currently limits users to a maximum of 3 distinct market depth requests. This same restriction applies to API clients, however API clients may make multiple market depth requests for the same security.”"},
            new ProviderErrorDef() { ErrCode= 310, RootsErr= 100, Desc= "Can’t find the subscribed market depth with tickerId="},
            new ProviderErrorDef() { ErrCode= 311, RootsErr= 106, Desc= "The origin is invalid."},
            new ProviderErrorDef() { ErrCode= 312, RootsErr= 106, Desc= "The combo details are invalid."},
            new ProviderErrorDef() { ErrCode= 313, RootsErr= 106, Desc= "The combo details for leg ” are invalid."},
            new ProviderErrorDef() { ErrCode= 314, RootsErr= 106, Desc= "Security type ‘BAG’ requires combo leg details."},
            new ProviderErrorDef() { ErrCode= 315, RootsErr= 100, Desc= "Stock combo legs are restricted to SMART order routing."},
            new ProviderErrorDef() { ErrCode= 316, RootsErr= 111, Desc= "Market depth data has been HALTED. Please re-subscribe."},
            new ProviderErrorDef() { ErrCode= 317, RootsErr= 111, Desc= "Market depth data has been RESET. Please empty deep book contents before applying any new entries."},
            new ProviderErrorDef() { ErrCode= 319, RootsErr= 106, Desc= "Invalid log level"},
            new ProviderErrorDef() { ErrCode= 320, RootsErr= 111, Desc= "Server error when reading an API client request."},
            new ProviderErrorDef() { ErrCode= 321, RootsErr= 111, Desc= "Server error when validating an API client request."},
            new ProviderErrorDef() { ErrCode= 322, RootsErr= 111, Desc= "Server error when processing an API client request."},
            new ProviderErrorDef() { ErrCode= 323, RootsErr= 111, Desc= "Server error= cause – s"},
            new ProviderErrorDef() { ErrCode= 324, RootsErr= 111, Desc= "Server error when reading a DDE client request (missing information)."},
            new ProviderErrorDef() { ErrCode= 325, RootsErr= 113, Desc= "Discretionary orders are not supported for this combination of exchange and order type."},
            new ProviderErrorDef() { ErrCode= 326, RootsErr= 114, Desc= "Unable to connect as the client id is already in use. Retry with a unique client id."},
            new ProviderErrorDef() { ErrCode= 327, RootsErr= 114, Desc= "Only API connections with clientId set to 0 can set the auto bind TWS orders property."},
            new ProviderErrorDef() { ErrCode= 328, RootsErr= 106, Desc= "Trailing stop orders can be attached to limit or stop-limit orders only."},
            new ProviderErrorDef() { ErrCode= 329, RootsErr= 100, Desc= "Order modify failed. Cannot change to the new order type."},
            new ProviderErrorDef() { ErrCode= 330, RootsErr= 107, Desc= "Only FA or STL customers can request managed accounts list."},
            new ProviderErrorDef() { ErrCode= 331, RootsErr= 100, Desc= "Internal error. FA or STL does not have any managed accounts."},
            new ProviderErrorDef() { ErrCode= 332, RootsErr= 106, Desc= "The account codes for the order profile are invalid."},
            new ProviderErrorDef() { ErrCode= 333, RootsErr= 106, Desc= "Invalid share allocation syntax."},
            new ProviderErrorDef() { ErrCode= 334, RootsErr= 106, Desc= "Invalid Good Till Date order"},
            new ProviderErrorDef() { ErrCode= 335, RootsErr= 106, Desc= "Invalid delta= The delta must be between 0 and 100."},
            new ProviderErrorDef() { ErrCode= 336, RootsErr= 106, Desc= "“The time or time zone is invalid. The correct format is hh=mm=ss xxx where xxx is an optionally specified time-zone. E.g.= 15=59=00 EST Note that there is a space between the time and the time zone. If no time zone is specified, local time is assumed.”"},
            new ProviderErrorDef() { ErrCode= 337, RootsErr= 106, Desc= "“The date, time, or time-zone entered is invalid. The correct format is yyyymmdd hh=mm=ss xxx where yyyymmdd and xxx are optional. E.g.= 20031126 15=59=00 ESTNote that there is a space between the date and time, and between the time and time-zone.”"},
            new ProviderErrorDef() { ErrCode= 338, RootsErr= 107, Desc= "Good After Time orders are currently disabled on this exchange."},
            new ProviderErrorDef() { ErrCode= 339, RootsErr= 113, Desc= "Futures spread are no longer supported. Please use combos instead."},
            new ProviderErrorDef() { ErrCode= 340, RootsErr= 106, Desc= "Invalid improvement amount for box auction strategy."},
            new ProviderErrorDef() { ErrCode= 341, RootsErr= 106, Desc= "“Invalid delta. Valid values are from 1 to 100. You can set the delta from the “”Pegged to Stock”” section of the Order Ticket Panel, or by selecting Page/Layout from the main menu and adding the Delta column.”"},
            new ProviderErrorDef() { ErrCode= 342, RootsErr= 113, Desc= "Pegged order is not supported on this exchange."},
            new ProviderErrorDef() { ErrCode= 343, RootsErr= 106, Desc= "“The date, time, or time-zone entered is invalid. The correct format is yyyymmdd hh=mm=ss xxx”"},
            new ProviderErrorDef() { ErrCode= 344, RootsErr= 101, Desc= "The account logged into is not a financial advisor account."},
            new ProviderErrorDef() { ErrCode= 345, RootsErr= 101, Desc= "Generic combo is not supported for FA advisor account."},
            new ProviderErrorDef() { ErrCode= 346, RootsErr= 101, Desc= "Not an institutional account or an away clearing account."},
            new ProviderErrorDef() { ErrCode= 347, RootsErr= 106, Desc= "Short sale slot value must be 1 (broker holds shares) or 2 (delivered from elsewhere)."},
            new ProviderErrorDef() { ErrCode= 348, RootsErr= 106, Desc= "Order not a short sale – type must be SSHORT to specify short sale slot."},
            new ProviderErrorDef() { ErrCode= 349, RootsErr= 113, Desc= "“Generic combo does not support “”Good After”” attribute.”"},
            new ProviderErrorDef() { ErrCode= 350, RootsErr= 113, Desc= "Minimum quantity is not supported for best combo order."},
            new ProviderErrorDef() { ErrCode= 351, RootsErr= 106, Desc= "“The “”Regular Trading Hours only”” flag is not valid for this order.”"},
            new ProviderErrorDef() { ErrCode= 352, RootsErr= 106, Desc= "Short sale slot value of 2 (delivered from elsewhere) requires location."},
            new ProviderErrorDef() { ErrCode= 353, RootsErr= 106, Desc= "Short sale slot value of 1 requires no location be specified."},
            new ProviderErrorDef() { ErrCode= 354, RootsErr= 107, Desc= "Not subscribed to requested market data."},
            new ProviderErrorDef() { ErrCode= 355, RootsErr= 106, Desc= "Order size does not conform to market rule."},
            new ProviderErrorDef() { ErrCode= 356, RootsErr= 113, Desc= "Smart-combo order does not support OCA group."},
            new ProviderErrorDef() { ErrCode= 357, RootsErr= 115, Desc= "Your client version is out of date."},
            new ProviderErrorDef() { ErrCode= 358, RootsErr= 113, Desc= "Smart combo child order not supported."},
            new ProviderErrorDef() { ErrCode= 359, RootsErr= 113, Desc= "Combo order only supports reduce on fill without block(OCA)."},
            new ProviderErrorDef() { ErrCode= 360, RootsErr= 113, Desc= "No whatif check support for smart combo order."},
            new ProviderErrorDef() { ErrCode= 361, RootsErr= 106, Desc= "Invalid trigger price."},
            new ProviderErrorDef() { ErrCode= 362, RootsErr= 106, Desc= "Invalid adjusted stop price."},
            new ProviderErrorDef() { ErrCode= 363, RootsErr= 106, Desc= "Invalid adjusted stop limit price."},
            new ProviderErrorDef() { ErrCode= 364, RootsErr= 106, Desc= "Invalid adjusted trailing amount."},
            new ProviderErrorDef() { ErrCode= 365, RootsErr= 107, Desc= "No scanner subscription found for ticker id="},
            new ProviderErrorDef() { ErrCode= 366, RootsErr= 116, Desc= "No historical data query found for ticker id="},
            new ProviderErrorDef() { ErrCode= 367, RootsErr= 106, Desc= "Volatility type if set must be 1 or 2 for VOL orders. Do not set it for other order types."},
            new ProviderErrorDef() { ErrCode= 368, RootsErr= 106, Desc= "Reference Price Type must be 1 or 2 for dynamic volatility management. Do not set it for non-VOL orders."},
            new ProviderErrorDef() { ErrCode= 369, RootsErr= 113, Desc= "Volatility orders are only valid for US options."},
            new ProviderErrorDef() { ErrCode= 370, RootsErr= 100, Desc= "“Dynamic Volatility orders must be SMART routed, or trade on a Price Improvement Exchange.”"},
            new ProviderErrorDef() { ErrCode= 371, RootsErr= 106, Desc= "VOL order requires positive floating point value for volatility. Do not set it for other order types."},
            new ProviderErrorDef() { ErrCode= 372, RootsErr= 100, Desc= "Cannot set dynamic VOL attribute on non-VOL order."},
            new ProviderErrorDef() { ErrCode= 373, RootsErr= 100, Desc= "Can only set stock range attribute on VOL or RELATIVE TO STOCK order."},
            new ProviderErrorDef() { ErrCode= 374, RootsErr= 106, Desc= "“If both are set, the lower stock range attribute must be less than the upper stock range attribute.”"},
            new ProviderErrorDef() { ErrCode= 375, RootsErr= 106, Desc= "Stock range attributes cannot be negative."},
            new ProviderErrorDef() { ErrCode= 376, RootsErr= 100, Desc= "The order is not eligible for continuous update. The option must trade on a cheap-to-reroute exchange."},
            new ProviderErrorDef() { ErrCode= 377, RootsErr= 106, Desc= "Must specify valid delta hedge order aux. price."},
            new ProviderErrorDef() { ErrCode= 378, RootsErr= 106, Desc= "Delta hedge order type requires delta hedge aux. price to be specified."},
            new ProviderErrorDef() { ErrCode= 379, RootsErr= 106, Desc= "Delta hedge order type requires that no delta hedge aux. price be specified."},
            new ProviderErrorDef() { ErrCode= 380, RootsErr= 106, Desc= "This order type is not allowed for delta hedge orders."},
            new ProviderErrorDef() { ErrCode= 381, RootsErr= 115, Desc= "Your DDE.dll needs to be upgraded."},
            new ProviderErrorDef() { ErrCode= 382, RootsErr= 106, Desc= "The price specified violates the number of ticks constraint specified in the default order settings."},
            new ProviderErrorDef() { ErrCode= 383, RootsErr= 106, Desc= "The size specified violates the size constraint specified in the default order settings."},
            new ProviderErrorDef() { ErrCode= 384, RootsErr= 106, Desc= "Invalid DDE array request."},
            new ProviderErrorDef() { ErrCode= 385, RootsErr= 120, Desc= "Duplicate ticker ID for API scanner subscription."},
            new ProviderErrorDef() { ErrCode= 386, RootsErr= 120, Desc= "Duplicate ticker ID for API historical data query."},
            new ProviderErrorDef() { ErrCode= 387, RootsErr= 113, Desc= "Unsupported order type for this exchange and security type."},
            new ProviderErrorDef() { ErrCode= 388, RootsErr= 106, Desc= "Order size is smaller than the minimum requirement."},
            new ProviderErrorDef() { ErrCode= 389, RootsErr= 100, Desc= "Supplied routed order ID is not unique."},
            new ProviderErrorDef() { ErrCode= 390, RootsErr= 100, Desc= "Supplied routed order ID is invalid."},
            new ProviderErrorDef() { ErrCode= 391, RootsErr= 106, Desc= "The time or time-zone entered is invalid. The correct format is hh=mm=ss xxx"},
            new ProviderErrorDef() { ErrCode= 392, RootsErr= 106, Desc= "Invalid order= contract expired."},
            new ProviderErrorDef() { ErrCode= 393, RootsErr= 106, Desc= "Short sale slot may be specified for delta hedge orders only."},
            new ProviderErrorDef() { ErrCode= 394, RootsErr= 106, Desc= "Invalid Process Time= must be integer number of milliseconds between 100 and 2000. Found="},
            new ProviderErrorDef() { ErrCode= 395, RootsErr= 111, Desc= "“Due to system problems, orders with OCA groups are currently not being accepted.”"},
            new ProviderErrorDef() { ErrCode= 396, RootsErr= 111, Desc= "“Due to system problems, application is currently accepting only Market and Limit orders for this contract.”"},
            new ProviderErrorDef() { ErrCode= 397, RootsErr= 111, Desc= "“Due to system problems, application is currently accepting only Market and Limit orders for this contract.”"},
            new ProviderErrorDef() { ErrCode= 398, RootsErr= 106, Desc= "cannot be used as a condition trigger."},
            new ProviderErrorDef() { ErrCode= 399, RootsErr= 100, Desc= "Order message error"},
            new ProviderErrorDef() { ErrCode= 400, RootsErr= 100, Desc= "Algo order error."},
            new ProviderErrorDef() { ErrCode= 401, RootsErr= 106, Desc= "Length restriction."},
            new ProviderErrorDef() { ErrCode= 402, RootsErr= 107, Desc= "Conditions are not allowed for this contract."},
            new ProviderErrorDef() { ErrCode= 403, RootsErr= 106, Desc= "Invalid stop price."},
            new ProviderErrorDef() { ErrCode= 404, RootsErr= 2, Desc= "Shares for this order are not immediately available for short sale. The order will be held while we attempt to locate the shares."},
            new ProviderErrorDef() { ErrCode= 405, RootsErr= 106, Desc= "The child order quantity should be equivalent to the parent order size."},
            new ProviderErrorDef() { ErrCode= 406, RootsErr= 107, Desc= "The currency is not allowed."},
            new ProviderErrorDef() { ErrCode= 407, RootsErr= 106, Desc= "The symbol should contain valid non-unicode characters only."},
            new ProviderErrorDef() { ErrCode= 408, RootsErr= 106, Desc= "Invalid scale order increment."},
            new ProviderErrorDef() { ErrCode= 409, RootsErr= 106, Desc= "Invalid scale order. You must specify order component size."},
            new ProviderErrorDef() { ErrCode= 410, RootsErr= 106, Desc= "Invalid subsequent component size for scale order."},
            new ProviderErrorDef() { ErrCode= 411, RootsErr= 116, Desc= "“The “”Outside Regular Trading Hours”” flag is not valid for this order.”"},
            new ProviderErrorDef() { ErrCode= 412, RootsErr= 116, Desc= "The contract is not available for trading."},
            new ProviderErrorDef() { ErrCode= 413, RootsErr= 106, Desc= "What-if order should have the transmit flag set to true."},
            new ProviderErrorDef() { ErrCode= 414, RootsErr= 106, Desc= "Snapshot market data subscription is not applicable to generic ticks."},
            new ProviderErrorDef() { ErrCode= 415, RootsErr= 100, Desc= "Wait until previous RFQ finishes and try again."},
            new ProviderErrorDef() { ErrCode= 416, RootsErr= 100, Desc= "RFQ is not applicable for the contract. Order ID="},
            new ProviderErrorDef() { ErrCode= 417, RootsErr= 106, Desc= "Invalid initial component size for scale order."},
            new ProviderErrorDef() { ErrCode= 418, RootsErr= 106, Desc= "Invalid scale order profit offset."},
            new ProviderErrorDef() { ErrCode= 419, RootsErr= 106, Desc= "Missing initial component size for scale order."},
            new ProviderErrorDef() { ErrCode= 420, RootsErr= 100, Desc= "Invalid real-time query."},
            new ProviderErrorDef() { ErrCode= 421, RootsErr= 100, Desc= "Invalid route."},
            new ProviderErrorDef() { ErrCode= 422, RootsErr= 100, Desc= "The account and clearing attributes on this order may not be changed."},
            new ProviderErrorDef() { ErrCode= 423, RootsErr= 112, Desc= "Cross order RFQ has been expired. THI committed size is no longer available. Please open order dialog and verify liquidity allocation."},
            new ProviderErrorDef() { ErrCode= 424, RootsErr= 100, Desc= "FA Order requires allocation to be specified."},
            new ProviderErrorDef() { ErrCode= 425, RootsErr= 100, Desc= "FA Order requires per-account manual allocations because there is no common clearing instruction. Please use order dialog Adviser tab to enter the allocation."},
            new ProviderErrorDef() { ErrCode= 426, RootsErr= 100, Desc= "None of the accounts have enough shares."},
            new ProviderErrorDef() { ErrCode= 427, RootsErr= 100, Desc= "Mutual Fund order requires monetary value to be specified."},
            new ProviderErrorDef() { ErrCode= 428, RootsErr= 100, Desc= "Mutual Fund Sell order requires shares to be specified."},
            new ProviderErrorDef() { ErrCode= 429, RootsErr= 100, Desc= "Delta neutral orders are only supported for combos (BAG security type)."},
            new ProviderErrorDef() { ErrCode= 430, RootsErr= 116, Desc= "“We are sorry, but fundamentals data for the security specified is not available.”"},
            new ProviderErrorDef() { ErrCode= 431, RootsErr= 106, Desc= "What to show field is missing or incorrect."},
            new ProviderErrorDef() { ErrCode= 432, RootsErr= 106, Desc= "Commission must not be negative."},
            new ProviderErrorDef() { ErrCode= 433, RootsErr= 106, Desc= "“Invalid “”Restore size after taking profit”” for multiple account allocation scale order.”"},
            new ProviderErrorDef() { ErrCode= 434, RootsErr= 106, Desc= "The order size cannot be zero."},
            new ProviderErrorDef() { ErrCode= 435, RootsErr= 106, Desc= "You must specify an account."},
            new ProviderErrorDef() { ErrCode= 436, RootsErr= 106, Desc= "“You must specify an allocation (either a single account, group, or profile).”"},
            new ProviderErrorDef() { ErrCode= 437, RootsErr= 106, Desc= "Order can have only one flag Outside RTH or Allow PreOpen."},
            new ProviderErrorDef() { ErrCode= 438, RootsErr= 100, Desc= "The application is now locked."},
            new ProviderErrorDef() { ErrCode= 439, RootsErr= 100, Desc= "Order processing failed. Algorithm definition not found."},
            new ProviderErrorDef() { ErrCode= 440, RootsErr= 100, Desc= "Order modify failed. Algorithm cannot be modified."},
            new ProviderErrorDef() { ErrCode= 441, RootsErr= 100, Desc= "Algo attributes validation failed="},
            new ProviderErrorDef() { ErrCode= 442, RootsErr= 107, Desc= "Specified algorithm is not allowed for this order."},
            new ProviderErrorDef() { ErrCode= 443, RootsErr= 100, Desc= "Order processing failed. Unknown algo attribute."},
            new ProviderErrorDef() { ErrCode= 444, RootsErr= 100, Desc= "Volatility Combo order is not yet acknowledged. Cannot submit changes at this time."},
            new ProviderErrorDef() { ErrCode= 445, RootsErr= 100, Desc= "The RFQ for this order is no longer valid."},
            new ProviderErrorDef() { ErrCode= 446, RootsErr= 106, Desc= "Missing scale order profit offset."},
            new ProviderErrorDef() { ErrCode= 447, RootsErr= 106, Desc= "Missing scale price adjustment amount or interval."},
            new ProviderErrorDef() { ErrCode= 448, RootsErr= 106, Desc= "Invalid scale price adjustment interval."},
            new ProviderErrorDef() { ErrCode= 449, RootsErr= 100, Desc= "Unexpected scale price adjustment amount or interval."},
            new ProviderErrorDef() { ErrCode= 481, RootsErr= 100, Desc= "Order size reduced."},
            new ProviderErrorDef() { ErrCode= 501, RootsErr= 114, Desc= "Already Connected."},
            new ProviderErrorDef() { ErrCode= 502, RootsErr= 114, Desc= "“Couldn’t connect to TWS. Confirm that “”Enable ActiveX and Socket Clients”” is enabled and connection port is the same as “”Socket Port”” on the TWS “”Edit->Global Configuration…->API->Settings”” menu.”"},
            new ProviderErrorDef() { ErrCode= 503, RootsErr= 115, Desc= "The TWS is out of date and must be upgraded."},
            new ProviderErrorDef() { ErrCode= 504, RootsErr= 114, Desc= "Not connected."},
            new ProviderErrorDef() { ErrCode= 505, RootsErr= 100, Desc= "Fatal Error= Unknown message id."},
            new ProviderErrorDef() { ErrCode= 507, RootsErr= 100, Desc= "Bad Message Length (Java-only)"},
            new ProviderErrorDef() { ErrCode= 585, RootsErr= 101, Desc= "FA Profile is not supported anymore, use FA Group instead"},
            new ProviderErrorDef() { ErrCode= 2100, RootsErr= 101, Desc= "New account data requested from TWS. API client has been unsubscribed from account data."},
            new ProviderErrorDef() { ErrCode= 2101, RootsErr= 101, Desc= "Unable to subscribe to account as the following clients are subscribed to a different account."},
            new ProviderErrorDef() { ErrCode= 2102, RootsErr= 100, Desc= "Unable to modify this order as it is still being processed."},
            new ProviderErrorDef() { ErrCode= 2103, RootsErr= 3, Desc= "A market data farm is disconnected."},
            new ProviderErrorDef() { ErrCode= 2104, RootsErr= 3, Desc= "Market data farm connection is OK"},
            new ProviderErrorDef() { ErrCode= 2105, RootsErr= 3, Desc= "A historical data farm is disconnected."},
            new ProviderErrorDef() { ErrCode= 2106, RootsErr= 3, Desc= "A historical data farm is connected."},
            new ProviderErrorDef() { ErrCode= 2107, RootsErr= 3, Desc= "A historical data farm connection has become inactive but should be available upon demand."},
            new ProviderErrorDef() { ErrCode= 2108, RootsErr= 3, Desc= "A market data farm connection has become inactive but should be available upon demand."},
            new ProviderErrorDef() { ErrCode= 2109, RootsErr= 3, Desc= "“Order Event Warning= Attribute “”Outside Regular Trading Hours”” is ignored based on the order type and destination. PlaceOrder is now processed.”"},
            new ProviderErrorDef() { ErrCode= 2110, RootsErr= 3, Desc= "Connectivity between TWS and server is broken. It will be restored automatically."},
            new ProviderErrorDef() { ErrCode= 2111, RootsErr= 3, Desc= "The Start and/or End Time for algo order BUY/SELL a contract was adjusted to use the next trading date. To modify this setting, use the Auto-adjust algo order date item on the Orders configuration page"},
            new ProviderErrorDef() { ErrCode= 2119, RootsErr= 3, Desc= "Market data farm is connecting."},
            new ProviderErrorDef() { ErrCode= 2130, RootsErr= 3, Desc= "Warning= products are trading on the basis of currency price with factor."},
            new ProviderErrorDef() { ErrCode= 2137, RootsErr= 3, Desc= "Cross Side Warning"},
            new ProviderErrorDef() { ErrCode= 2152, RootsErr= 3, Desc= "Market depth smart depth exchanges."},
            new ProviderErrorDef() { ErrCode= 2158, RootsErr= 3, Desc= "Sec-def data farm connection is OK"},
            new ProviderErrorDef() { ErrCode= 2168, RootsErr= 3, Desc= "Etrade Only Not Supported Warning"},
            new ProviderErrorDef() { ErrCode= 2169, RootsErr= 3, Desc= "Firm Quote Only Not Supported Warning"},
            new ProviderErrorDef() { ErrCode= 10000, RootsErr= 100, Desc= "Cross currency combo error."},
            new ProviderErrorDef() { ErrCode= 10001, RootsErr= 100, Desc= "Cross currency vol error."},
            new ProviderErrorDef() { ErrCode= 10002, RootsErr= 100, Desc= "Invalid non-guaranteed legs."},
            new ProviderErrorDef() { ErrCode= 10003, RootsErr= 100, Desc= "IBSX not allowed."},
            new ProviderErrorDef() { ErrCode= 10005, RootsErr= 100, Desc= "Read-only models."},
            new ProviderErrorDef() { ErrCode= 10006, RootsErr= 106, Desc= "Missing parent order."},
            new ProviderErrorDef() { ErrCode= 10007, RootsErr= 106, Desc= "Invalid hedge type."},
            new ProviderErrorDef() { ErrCode= 10008, RootsErr= 106, Desc= "Invalid beta value."},
            new ProviderErrorDef() { ErrCode= 10009, RootsErr= 106, Desc= "Invalid hedge ratio."},
            new ProviderErrorDef() { ErrCode= 10010, RootsErr= 106, Desc= "Invalid delta hedge order."},
            new ProviderErrorDef() { ErrCode= 10011, RootsErr= 113, Desc= "Currency is not supported for Smart combo."},
            new ProviderErrorDef() { ErrCode= 10012, RootsErr= 106, Desc= "Invalid allocation percentage"},
            new ProviderErrorDef() { ErrCode= 10013, RootsErr= 100, Desc= "Smart routing API error (Smart routing opt-out required)."},
            new ProviderErrorDef() { ErrCode= 10014, RootsErr= 106, Desc= "PctChange limits."},
            new ProviderErrorDef() { ErrCode= 10015, RootsErr= 100, Desc= "Trading is not allowed in the API."},
            new ProviderErrorDef() { ErrCode= 10016, RootsErr= 100, Desc= "Contract is not visible."},
            new ProviderErrorDef() { ErrCode= 10017, RootsErr= 100, Desc= "Contracts are not visible."},
            new ProviderErrorDef() { ErrCode= 10018, RootsErr= 2, Desc= "Orders use EV warning."},
            new ProviderErrorDef() { ErrCode= 10019, RootsErr= 2, Desc= "Trades use EV warning."},
            new ProviderErrorDef() { ErrCode= 10020, RootsErr= 106, Desc= "Display size should be smaller than order size./td>"},
            new ProviderErrorDef() { ErrCode= 10021, RootsErr= 106, Desc= "Invalid leg2 to Mkt Offset API."},
            new ProviderErrorDef() { ErrCode= 10022, RootsErr= 106, Desc= "Invalid Leg Prio API."},
            new ProviderErrorDef() { ErrCode= 10023, RootsErr= 106, Desc= "Invalid combo display size API."},
            new ProviderErrorDef() { ErrCode= 10024, RootsErr= 106, Desc= "Invalid don’t start next legin API."},
            new ProviderErrorDef() { ErrCode= 10025, RootsErr= 106, Desc= "Invalid leg2 to Mkt time1 API."},
            new ProviderErrorDef() { ErrCode= 10026, RootsErr= 106, Desc= "Invalid leg2 to Mkt time2 API."},
            new ProviderErrorDef() { ErrCode= 10027, RootsErr= 106, Desc= "Invalid combo routing tag API."},
            new ProviderErrorDef() { ErrCode= 10090, RootsErr= 100, Desc= "Part of requested market data is not subscribed."},
            new ProviderErrorDef() { ErrCode= 10147, RootsErr= 100, Desc= "Order to be canceled was not found."},
            new ProviderErrorDef() { ErrCode= 10148, RootsErr= 100, Desc= "“OrderId that needs to be cancelled can not be cancelled, state=”"},
            new ProviderErrorDef() { ErrCode= 10186, RootsErr= 100, Desc= "Requested market data is not subscribed. Delayed market data is not enabled"},
            new ProviderErrorDef() { ErrCode= 10187, RootsErr= 100, Desc= "Failed to request historical ticks=No market data permissions"},
            new ProviderErrorDef() { ErrCode= 10189, RootsErr= 100, Desc= "Failed to request tick-by-tick data. Invalid Real-time Query"},
            new ProviderErrorDef() { ErrCode= 10197, RootsErr= 100, Desc= "No market data during competing session"},
            new ProviderErrorDef() { ErrCode= 10225, RootsErr= 100, Desc= "“Bust event occurred, current subscription is deactivated. Please resubscribe real-time bars immediately”"},
            new ProviderErrorDef() { ErrCode= 10230, RootsErr= 100, Desc= "“You have unsaved FA changes. Please retry ‘request FA’ operation later, when ‘replace FA’ operation is complete”"},
            new ProviderErrorDef() { ErrCode= 10231, RootsErr= 100, Desc= "The following Groups and/or Profiles contain invalid accounts="},
            new ProviderErrorDef() { ErrCode= 10233, RootsErr= 100, Desc= "Defaults were inherited from CASH preset during the creation of this order."},
            new ProviderErrorDef() { ErrCode= 10234, RootsErr= 100, Desc= "The Decision Maker field is required and not set for this order (non-desktop)."},
            new ProviderErrorDef() { ErrCode= 10235, RootsErr= 100, Desc= "The Decision Maker field is required and not set for this order (ibbot)."},
            new ProviderErrorDef() { ErrCode= 10236, RootsErr= 100, Desc= "Child has to be AON if parent order is AON"},
            new ProviderErrorDef() { ErrCode= 10237, RootsErr= 100, Desc= "All or None ticket can route entire unfilled size only"},
            new ProviderErrorDef() { ErrCode= 10238, RootsErr= 100, Desc= "Some error occured during communication with Advisor Setup web-app"},
            new ProviderErrorDef() { ErrCode= 10239, RootsErr= 100, Desc= "This order will affect one or more accounts that are flagged because they do not fit the required risk score criteria prescribed by the group/profile/model allocation."},
            new ProviderErrorDef() { ErrCode= 10240, RootsErr= 100, Desc= "You must enter a valid Price Cap."},
            new ProviderErrorDef() { ErrCode= 10241, RootsErr= 100, Desc= "Order Quantity is expressed in monetary terms. Modification is not supported via API. Please use desktop version to revise this order."},
            new ProviderErrorDef() { ErrCode= 10242, RootsErr= 100, Desc= "Fractional-sized order cannot be modified via API. Please use desktop version to revise this order."},
            new ProviderErrorDef() { ErrCode= 10243, RootsErr= 100, Desc= "Fractional-sized order cannot be placed via API. Please use desktop version to place this order."},
            new ProviderErrorDef() { ErrCode= 10244, RootsErr= 100, Desc= "Cash Quantity cannot be used for this order"},
            new ProviderErrorDef() { ErrCode= 10245, RootsErr= 113, Desc= "This financial instrument does not support fractional shares trading"},
            new ProviderErrorDef() { ErrCode= 10246, RootsErr= 113, Desc= "This order doesn’t support fractional shares trading"},
            new ProviderErrorDef() { ErrCode= 10247, RootsErr= 113, Desc= "Only IB SmartRouting supports fractional shares"},
            new ProviderErrorDef() { ErrCode= 10248, RootsErr= 117, Desc= "doesn’t have permission to trade fractional shares"},
            new ProviderErrorDef() { ErrCode= 10249, RootsErr= 113, Desc= "“=””””> order doesn’t support fractional shares”"},
            new ProviderErrorDef() { ErrCode= 10250, RootsErr= 106, Desc= "The size does not conform to the minimum variation of for this contract"},
            new ProviderErrorDef() { ErrCode= 10251, RootsErr= 113, Desc= "Fractional shares are not supported for allocation orders"},
            new ProviderErrorDef() { ErrCode= 10252, RootsErr= 113, Desc= "This non-close-position order doesn’t support fractional shares trading"},
            new ProviderErrorDef() { ErrCode= 10253, RootsErr= 113, Desc= "Clear Away orders are not supported for multi-leg combo with attached hedge."},
            new ProviderErrorDef() { ErrCode= 10254, RootsErr= 112, Desc= "Invalid Order= bond expired"},
            new ProviderErrorDef() { ErrCode= 10268, RootsErr= 113, Desc= "The ‘EtradeOnly’ order attribute is not supported"},
            new ProviderErrorDef() { ErrCode= 10269, RootsErr= 113, Desc= "The ‘firmQuoteOnly’ order attribute is not supported"},
            new ProviderErrorDef() { ErrCode= 10270, RootsErr= 113, Desc= "The ‘nbboPriceCap’ order attribute is not supported"},
            new ProviderErrorDef() { ErrCode= 10276, RootsErr= 107, Desc= "News feed is not allowed"},
            new ProviderErrorDef() { ErrCode= 10277, RootsErr= 117, Desc= "News feed permissions required"},
            new ProviderErrorDef() { ErrCode= 10278, RootsErr= 100, Desc= "Duplicate WSH metadata request"},
            new ProviderErrorDef() { ErrCode= 10279, RootsErr= 100, Desc= "Failed request WSH metadata"},
            new ProviderErrorDef() { ErrCode= 10280, RootsErr= 100, Desc= "Failed cancel WSH metadata"},
            new ProviderErrorDef() { ErrCode= 10281, RootsErr= 100, Desc= "Duplicate WSH event data request"},
            new ProviderErrorDef() { ErrCode= 10282, RootsErr= 100, Desc= "WSH metadata not requested"},
            new ProviderErrorDef() { ErrCode= 10283, RootsErr= 100, Desc= "Fail request WSH event data"},
            new ProviderErrorDef() { ErrCode= 10284, RootsErr= 100, Desc= "Fail cancel WSH event data"},
            new ProviderErrorDef() { ErrCode= 10285, RootsErr= 115, Desc= "Your API version does not support fractional sizing rules. Please upgrade to at least version 163"},
            new ProviderErrorDef() { ErrCode= 10038, RootsErr= 114, Desc= "An operation was attempted on something that is not a socket."}
        };

        public static ProviderErrorDef? GetProvErrorDef(int code)
        {
            for (int ndx = 0; ndx < ErrorDef.Count; ndx++)
            {
                if (code == ErrorDef[ndx].ErrCode)
                {
                    return ErrorDef[ndx];
                }
            }
            return null;
        }

        public static int[] ServerErrors = new int[] {
            501 /* ALREADY_CONNECTED */, 
            502 /*COULD_NOT_CONNECT*/, 
            504 /*NOT_CONNECTED*/,
            1100 /*CONNECTIVITY_BETWEEN_IB_AND_TWS_LOST*/
        };

        public static int[] TickerErrors = new int[] {
            200 /*SECURITY_DEFINITION*/, 
            313 /*INVALID_COMBO_LEG*/, 
            321 /*VALIDATE_REQ_ERROR*/, 
            322 /*PROCESS_REQ_ERROR*/,
            429 /*DELTA_NEUTRAL_COMBO_ONLY*/, 
            10154 /*LEG_NOT_SUPPORTED*/,
            10167 /*REQUESTED_MARKET_DATA_NOT_SUBSCRIBED*/,
            579 /*INVALID_SYMBOL*/
        };

    }
}
